### ISSUE TITLE
Learning Styles Theory Countered by Current Research

### ISSUE THREAD

**Issue by emanette** [Ada-Developers-Academy/ada-build#114]
Current research has shown that the theory of learning styles hasn't been supported in the literature. People tend to use all styles of learning, and there's no correlation between successful learning and using a learning style that you believe fits you best.

Here are some references:
1) https://www.psychologicalscience.org/news/releases/learning-styles-debunked-there-is-no-evidence-supporting-auditory-and-visual-learning-psychologists-say.html
2) https://www.scientificamerican.com/article/the-problem-with-learning-styles/
3) https://journals.sagepub.com/doi/abs/10.1177/1477878515606621

The second reference contains studying/learning method suggestions that have been shown to be effective.

**Comment by CheezItMan** [comment]
This matches my education as well.
