### ISSUE TITLE
Possibly ambiguous Comment section at the end of 01_hello_world example shown in video

### ISSUE THREAD

**Issue by anselrognlie** [Ada-Developers-Academy/ada-build#134]
Commenting only seems to be available if a user makes a local copy of of the Colab notebook (am I missing something?).  If a user is following along with the video, they might reach the bottom and want to record their thought, but the icon and Comment display do nothing (they're just an image), and there is no other obvious Comment functionality.

The environment setup text *does* mention that a notebook can be copied to make it your own, but perhaps something should be explicitly added with reference to adding comments?

**Comment by beccaelenzil** [comment]
I added more emphasis to choosing **File** --> **Save a copy in Drive**. Not sure if something else is needed.

**Comment by anselrognlie** [comment]
So it does sound like the reader must make a copy in order to enable the Commenting tool.  In that case, I would suggest replacing:
>Lastly, to keep the colab notebook as your own and save your changes, choose **File --> Save a copy in Drive**.

with something like:

---
Lastly, in order to save the changes that you make to any live code blocks in a Colab notebook, and to enable the ability to add comments, **you must save a copy of *every* notebook you open to your own Google Drive**.  If you do not, then any code changes will be lost when you close the notebook, and the Comment tool will not become available.  To make a copy, just after you open a notebook click the `Copy to Drive` button right below the menu bar and follow any prompts.  The copied notebook will be opened and you will be able to preserve your code changes and comments.

---
(N.B. The Copy to Drive button doesn't appear for notebooks for which you already have editing rights, which is probably why you don't see it in existing Drive notebooks, but you will see it if you open the github versions.  Those seem to always open as read-only, so they are a good proxy for the experience that an external reader will encounter.)

**Comment by beccaelenzil** [comment]
I added this text about making your own copy to the beginning of the hello world notebook, and will add this reminder to the beginning of each notebook.
