### ISSUE TITLE
Inconsistent use of print() in 02_programming_grammar under Determining the type

### ISSUE THREAD

**Issue by anselrognlie** [Ada-Developers-Academy/ada-build#135]
The first example `print(type(1))` explicitly uses `print`, even though the description text mentions that the results are output even without calling `print`.

If the results were equivalent, this would be an interesting point of comparison, but by explicitly calling `print` on the result of `type` the output is noisier `<class 'int'>` than if the type is just evaluated for output `int`, and that difference is not addressed in the description.

Either the samples should all omit `print`, resulting in equivalent output, or the difference in output when using or not using `print` should be addressed, which is possibly too advanced a topic at this point in the introduction.

**Comment by beccaelenzil** [comment]
I added a separate section for  `print(type(1))` to mention what a class is.
