### ISSUE TITLE
02_programming_grammar Strings Interpolation and Methods grammar, typo, and suggestions

### ISSUE THREAD

**Issue by anselrognlie** [Ada-Developers-Academy/ada-build#138]
The comma in

You can create a string by surrounding the sequence of characters with double or single quotes, both "hello" and 'hello' are strings.

should be a semicolon, as the two clauses are independent, but closely-related.

You can create a string by surrounding the sequence of characters with double or single quotes; both "hello" and 'hello' are strings.

---

In

_Methods_ are _functions_ that can be called on instances of a class

This is the first mention of the term *instances*.  Consider calling out an explanation for instances as they relate to classes.

---

There is a typo in

They are a more specific name for a _function_ and are called using parenthese `()`.

It should be parentheses.

---

The sentence

_String interpolation_ is a process substituting values of variables into placeholders in a string.

might flow a little better as

_String interpolation_ is the process of substituting values of variables into placeholders in a string.

The original version has an uncomfortable stop between process and substituting where it's not clear that the clause is continuing.

**Comment by beccaelenzil** [comment]
I made all suggested changes aside from adding more details on an instance of a class. I added classes to the list of topics we'll talk about more later.
