### ISSUE TITLE
02_programming_grammar Indexing/Slicing typo and feedback

### ISSUE THREAD

**Issue by anselrognlie** [Ada-Developers-Academy/ada-build#139]
In

- `string[I]` will provide give a single character

remove give (provide is used in the remaining examples)

---

The term *index* first appears under the description of slicing using the two-value syntax, without a previous introduction, even though the section is called Indexing/Slicing.  Consider explicitly introducing indexing in a manner similar to how slicing is introduced, perhaps:

Indexing refers to retrieving a single value from a group, in this case a string of characters, by its position in that group.  Alternatively, it can refer to the method by which we label those positions.

---

The passage starting 

Finally, note that in Python, indexing starts at the value `0`.

Is not the final passage.  Consider just

Note that in Python,

or if more emphasis is desired

It is important to note that in Python,

**Comment by beccaelenzil** [comment]
changes made
