### ISSUE TITLE
02_programming_grammar Practice Problems missing code block and suggestion

### ISSUE THREAD

**Issue by anselrognlie** [Ada-Developers-Academy/ada-build#142]
In

Complete each section by hand, then check your answers by running code in a code block.

consider adding *the*, that is

Complete each section by hand, then check your answers by running the code in a code block.

---

Also, consider adding an empty code block directly below the Variables and Assignment section, as the other two coding practice problems have.

In that case, modify the line to

Complete each section by hand, then check your answers by running the code in the code block below.

**Comment by beccaelenzil** [comment]
change made
