### ISSUE TITLE
03_branching Exercise: Conditionals Syntax shows some practice output by default

### ISSUE THREAD

**Issue by anselrognlie** [Ada-Developers-Academy/ada-build#147]
Is there a way to clear (and save that it was cleared) a previous run displayed for the practice code blocks?

The exercises ask the reader to predict the output, but the output is already being shown for Practice #1 and Practice #2.  Practice #3 properly does not show any previous output, allowing the reader to predict on their own.

**Comment by anselrognlie** [comment]
It appears that if the output of a live code block was not cleared before the notebook is exported to github, the output will be shown by default in the resulting github copy.  Users with editing permissions should be reminded to clear any output fields they run in the Drive copy, and whenever a fresh copy of a notebook is exported to github, the reviewer in charge should ensure that all output fields have been cleared prior to export.

**Comment by beccaelenzil** [comment]
I will choose the "omit all output when saving notebook" setting, and that will deal with this issue.
