### ISSUE TITLE
05_loops_iteration Loop Tables for Debugging text edits

### ISSUE THREAD

**Issue by anselrognlie** [Ada-Developers-Academy/ada-build#200]
- change from descriptive mood to inclusive
- you → us
- revised the analysis text
- added alternative solution
---
### Loop Tables for Debugging

Let's start by building a loop table to help figure out what's happening.  Loop tables let us mentally walk through each step in our loop code.

| Iteration 	| i 	| sum 	|  i <= 5 	|
|-	|-	|-	|-	|
| 1 	| 2 	| 2 	| true 	| 
| 2 	| 3 	| 5 	| true 	| 
| 3 	| 4 	| 9 	| true 	| 
| 4 	| 5 	| 14 	| true 	| 
| 5 	| 6 	| 20 	| false 	| 

Reviewing this loop table, we can see that by the time we added `i` to `sum` in the first iteration, `i` had already advanced to 2.  We also added up all the way to 6, rather than stopping at 5.  Both of these are caused by incrementing `i` prior to using it in the addition statement.  We can confirm this by moving the addition before the increment, resulting in the following working code:
```python
# insert existing code block
```
Before moving on, we can again consider an alternative solution that uses `for` instead of `while`.  As before, this can simplify the logic of our code by removing the need to manually manage the loop control variable.  Consider the following.
```python
sum = 0

for i in range(1, 6):  # generates 1, 2, 3, 4, 5.  As usual, the stop value, 6, is excluded.
    sum = sum + i

print(f"The Sum is {sum}")  # 1 + 2 + 3 + 4 + 5 = 15
```
Notice that we have removed the need to initialize `i` before the loop, nor do we need to increment `i` within the loop, making it impossible to perform the addition and the increment in the wrong order.  When choosing between `for` and `while` loops, the degree to which each loop style makes it *difficult* to express our intent *incorrectly* is an important consideration.

**Comment by anselrognlie** [comment]
migrated to notebook comments

**Comment by DEJ4Coding** [comment]
TAKE ME OFF THIS EMAIL CHAIN NOWWWWWW IM SICK OF GETTING 100s of emails a day THIS IS SPAM!!

**Comment by anselrognlie** [comment]
Hi, Dana.

I'm sorry that you're receiving unwanted notifications.  It appears that
some time in the past, you added this repository to your watch list.  Your
account shows up under the list of accounts watching the repository.  If
you visit the repository page (
https://github.com/Ada-Developers-Academy/ada-build) you should be able to
click the Watch dropdown list and change your watch settings.  That's a
setting that you control.  Unfortunately, the admins of this repo can't
change it for you (and I'm not even an admin myself).  Alternatively, take
a look at your settings at https://github.com/watching or
https://github.com/notifications/subscriptions to see whether it's easier
for you to change the setting there.  Finally, you could consider creating
an inbox rule (if your mail platform supports it) to filter out
notifications from repos you aren't actively using.  However this would
just be a stop-gap.  Modifying your Watch settings will be the real
solution.
