### ISSUE TITLE
Solution for "Rock, Paper, Scissors" 05_loops_iteration is the same one as for 04_functions

### ISSUE THREAD

**Issue by kmalakhova** [Ada-Developers-Academy/ada-build#205]
Solution links lead to two different files, but the content is the same

**Comment by beccaelenzil** [comment]
The logic is the same in each of them, but the one linked in lesson 05 has a while loop: https://repl.it/@BeccaElenzil/Rock-Paper-Scissors-v3#main.py

This is the file linked in Lesson 04, which just is the function: https://repl.it/@BeccaElenzil/Rock-Paper-Scissors-v2#main.py

**Comment by kmalakhova** [comment]
I see it's been fixed, thank you!
