### ISSUE TITLE
03_branching typo

### ISSUE THREAD

**Issue by trnle** [Ada-Developers-Academy/ada-build#206]
There's a typo in the first sentence of the note. The if statement uses the escaped apostrophe because the string is in single quotes, not double quotes.

<img width="1074" alt="Screen Shot 2020-08-26 at 2 21 00 PM" src="https://user-images.githubusercontent.com/58532396/91347312-bb879100-e7a7-11ea-9e67-6ec976dab1da.png">

**Comment by beccaelenzil** [comment]
corrected.
