### ISSUE TITLE
Conditionals diagram solution links to rock, paper, scissors solution

### ISSUE THREAD

**Issue by trnle** [Ada-Developers-Academy/ada-build#207]
Located in 03_branching file. Links to RPS solution that's similar to the project solution at the end of the assignment page.

<img width="735" alt="Screen Shot 2020-08-26 at 2 42 22 PM" src="https://user-images.githubusercontent.com/58532396/91349357-cee82b80-e7aa-11ea-9390-8c83b44ea906.png">

**Comment by beccaelenzil** [comment]
corrected
