### ISSUE TITLE
"Open in Colab" link "Intro-to-Python," locked content 

### ISSUE THREAD

**Issue by KitSutliff** [Ada-Developers-Academy/ada-build#208]
Thank you for designing this course.  This may be an issue of user error, but I am repeatedly encountering this "Content is blocked" screen :(

(image attached)

Thank you again for your work :)

![Sad Face Screen Shot](https://user-images.githubusercontent.com/38538497/92289179-6690fc80-eec4-11ea-98d1-fe53a495ee74.png)

**Comment by CheezItMan** [comment]
I've replaced the notebook file and it should open now.
