### ISSUE TITLE
07 Account Generator Project (v2) links to an outdated/incomplete example solution

### ISSUE THREAD

**Issue by jittania** [Ada-Developers-Academy/ada-build#209]
The provided example solution uses data that doesn't match the question (appears to be modified from the first version of the account generator project, which also appears to be outdated - noted in a separate issue). This is problematic because the current version of this problems asks you to append the last digits of the student ID to the email username, which is not demonstrated in this example solution. Also appears to be incomplete - line 17 comment "# create dictionary " is followed by a blank space. There is no code component addressing or updating the print functionality either:
![Screen Shot 2020-09-09 at 9 44 08 PM](https://user-images.githubusercontent.com/67732598/92682626-a6e9e380-f2e5-11ea-8b2b-f7b67ba0c01f.png)

**Comment by beccaelenzil** [comment]
A corrected solution has been linked.
