### ISSUE TITLE
02 Practice Problems 3. Strings

### ISSUE THREAD

**Issue by einismine** [Ada-Developers-Academy/ada-build#210]
For the following practice problems, the code block does not output my_string.

`# problem 3.3
my_string = "Ada"
my_string += " Lovelace"

# problem 3.4
my_string = "Ada"
my_string += " codes" + " it!"
`

**Comment by beccaelenzil** [comment]
To output `my_string`, you need to type `my_string` on the final line of the code block or `print(my_string)`. This exercise not meant to print my string so that you can test your knowledge.
