### ISSUE TITLE
Lesson 3 : Branching Practice #03

### ISSUE THREAD

**Issue by scantea** [Ada-Developers-Academy/ada-build#211]
The example offered for the weather problem works, could this solution also be a good example solution?
# Practice #3
temp = 0

if temp == 100:
    print("It's ONE HUNDDRED DEGREES outside!")
elif 50 < temp < 100:
    print("It's warm outside")
elif 0 < temp < 50:
    print("It's a bit chilly outside")  
elif temp == 0:
    print("It's ZERO DEGREES outside!")

**Comment by SterlingSunshine** [comment]
Additionally, is "HUNDDRED" intended to be spelled like that? As opposed to "HUNDRED"?

**Comment by beccaelenzil** [comment]
This solution works, though it can often be best practice put the most specific scenarios first.

I'll change HUNDDRED to HUNDRED :)
