### ISSUE TITLE
Lesson 3: Branching

### ISSUE THREAD

**Issue by scantea** [Ada-Developers-Academy/ada-build#212]
The solution to paper scissors rock link does not work on any of my browsers. Repl.it webpage says the maximum players have been reached and the code does not run

**Comment by libgerber** [comment]
I'm also getting the same error message "Multiplayer Limit Reached" for repl.it link to first rock paper scissors solution.

**Comment by zcjenny** [comment]
Same for me! I've completed the tasks and would like to check the best solution, but unable to open on Repl.it.

**Comment by beccaelenzil** [comment]
It looks like I accidentally provided edit privilege to this repl. There will be a corrected link by Friday 10/23.
