### ISSUE TITLE
Lesson 3: 03_branching

### ISSUE THREAD

**Issue by GetlinN** [Ada-Developers-Academy/ada-build#213]
03_branching -> Practice Problems -> "1. Diagram → Code"

[Link to the cell "You can few our solution here."](https://colab.research.google.com/drive/1Q5H9bE2093-9w1RpFKoyDwH4SLMRW_HS#scrollTo=NoORB9lBILhB)

The link provides a solution to some other different problem, but not to the one, listed in the section "1. Diagram → Code"

**Comment by beccaelenzil** [comment]
It looks like I accidentally provided edit privilege to this repl. There will be a corrected link by Friday 10/23.
