### ISSUE TITLE
Lesson 4: link to different problem solution

### ISSUE THREAD

**Issue by GetlinN** [Ada-Developers-Academy/ada-build#214]
https://colab.research.google.com/drive/1W6HPHvzrhLFubxWa5bTFmEQSYe0kH0c0#scrollTo=f9T-RrXeWJsG

04_functions -> Project: Rock, Paper, Scissors - v2

[Link to the cell "You can few our solution here."](https://colab.research.google.com/github/Ada-Developers-Academy/ada-build/blob/master/intro-to-python/04_functions.ipynb#scrollTo=f9T-RrXeWJsG)

The link provides a solution to a different problem.

<img width="977" alt="Screen Shot 2020-10-09 at 1 53 12 PM" src="https://user-images.githubusercontent.com/43629191/95630927-8ffaf600-0a37-11eb-8f5d-9a2894e06ea2.png">

**Comment by beccaelenzil** [comment]
It looks like I accidentally provided edit privilege to this repl. I will aim to have a corrected link by Friday 10/23.

**Comment by beccaelenzil** [comment]
I accidentally gave edit privilege to this repl. It is correct now.
