### ISSUE TITLE
03 Branching practice problem 1

### ISSUE THREAD

**Issue by camthecoder2020** [Ada-Developers-Academy/ada-build#216]
The solution link provided for practice problem 1 on Diagram -> Code is incorrect. The link takes you to a solution for the rock paper scissors question - see below:

[https://repl.it/@BeccaElenzil/conditionals-diagram#main.py](url)

**Comment by beccaelenzil** [comment]
It looks like I accidentally provided edit privilege to this repl. I will aim to have a corrected link by Friday 10/23.
