### ISSUE TITLE
Minor Changes Throughout Ada Build

### ISSUE THREAD

**Issue by krj8** [Ada-Developers-Academy/ada-build#218]
#### Lesson 00 Ada Programming Languages
- Remove extra word under Overview: “Are some languages are better at certain things than others?”

#### Lesson 00 Python Environment 
- Change "use" to "used" under Learning Goals : “Understand how repl.it will be use.”

#### Lesson 00 Python Environment
 - Missing apostrophe under Google Colab: “Lets take a look at the Preparing to code Notebook.”

#### Lesson 02 Programming Grammar
- Remove extra word under Indexing/Slicing: “string[i] will provide give a single character”

#### Lesson 03 Branching
- Replace word under Diagram —> Code: “You can few our solution here."

#### Lesson 04 Functions
- Replace second “int” with “integer” under New Functions: “int converts data to the int class.”

#### Lesson 06 Lists
- Combine two sentences under Using Built-In Methods: “Recall that functions are invoked with the syntax function_name(arguments) and methods are invoked with the syntax.
object.method_name(arguments).”

**Comment by beccaelenzil** [comment]
Thanks for the feedback. The corrections were made.
