### ISSUE TITLE
Typo - 05 Loops and Iterators Chapter

### ISSUE THREAD

**Issue by Kbhlee2121** [Ada-Developers-Academy/ada-build#219]
Hello! 

_I noticed that the sample solution given for Rock, Paper, Scissors v3 in repl.it was producing partially incorrect outputs such as in the screenshot below:_ 

![image](https://user-images.githubusercontent.com/71902467/97796502-efc86500-1bcf-11eb-8b85-733e520406c8.png)

_Looking at the bottom of the solution (pasted below for convenience), I found parentheses were missing from choose_rps and that there were one too many spaces after the word "chose"._

print("Welcome to Rock, Paper, Scissors!\n")
while play == True:
  **player1 = choose_rps  
  player2 = choose_rps**

  print("Player 1 **chose** ", player1, ".")
  print("Player 2 **chose** ", player2, ".")

  rps_function(player1, player2)

  print(" ")

  play = play_again()

print("Thank you for playing!")   

_I am not entirely sure of what is the best solution, but I found that adding parentheses ( "()" ) after choose_rps and deleting the space after the word, "chose," helped resolve the issues like so:_

print("Welcome to Rock, Paper, Scissors!\n")
while play == True:
  **player1 = choose_rps()
  player2 = choose_rps()**

  print("Player 1 **chose"**, player1, ".")
  print("Player 2 **chose"**, player2, ".")

  rps_function(player1, player2)
 
  print(" ")

  play = play_again()

print("Thank you for playing!")   

![image](https://user-images.githubusercontent.com/71902467/97796700-b2190b80-1bd2-11eb-80ed-2dd7fd0ca91a.png)

_If there is a better or another way to fix this, please let us know. If these were intentional, please disregard!_

Thanks!
K.L.

**Comment by beccaelenzil** [comment]
Good catch! This is the correct solution. We could also use [f-strings] (https://docs.python.org/3/reference/lexical_analysis.html#f-strings) formatting the output. ` print(f"Player 1 chose {player1}.")`.

The correction has been made. Thanks!
