### ISSUE TITLE
Minor Typo in Programming in Python 02

### ISSUE THREAD

**Issue by ashleybaker3** [Ada-Developers-Academy/ada-build#221]
![Ada Build Spelling Error](https://user-images.githubusercontent.com/75815133/102307709-dda14c80-3f19-11eb-9cd4-bfa0c1a809e4.png)

"This means that Python hit and error at the end of the line" should be "This means that Python hit _**an**_ error at the end of the line"

Thank you!
Ashley

**Comment by beccaelenzil** [comment]
corrected. thank you!
