### ISSUE TITLE
Dictionaries missing "solution worked" verification?

### ISSUE THREAD

**Issue by sarah-541** [Ada-Developers-Academy/ada-build#224]
Hi there! I think I found another little issue. Is **Exercise: Create a Dictionary** in **Lesson 7: Dictionaries** missing a statement to print out that the solution worked? Or maybe it's intended that the absence of an error message is our confirmation but thought I'd share just in case it's not intentional. 

![image](https://user-images.githubusercontent.com/73004816/103159429-31176400-477e-11eb-851f-ba5a467734fe.png)

**Comment by beccaelenzil** [comment]
Indeeed. With [`assert` statements](https://www.w3schools.com/python/ref_keyword_assert.asp), nothing happens if the condition is true. An `AssertionError` is raised if the condition returns `False`. I added this line for clarity and to be consistent with other lessons. Thanks!

```
# If the program gets here, the code works!
print("Your solution works!")
```
