### ISSUE TITLE
Typo in Dictionaries lesson

### ISSUE THREAD

**Issue by sarah-541** [Ada-Developers-Academy/ada-build#225]
I found another typo. Sorry to be bombarding you with issues! It's in **Lesson 7: Dictionaries**. Screenshot attached!
![image](https://user-images.githubusercontent.com/73004816/103159638-a421da00-4780-11eb-8dfe-f44a075eb3a9.png)

**Comment by beccaelenzil** [comment]
Thank you! Fixed. An no apologies necessary -- we appreciate the feedback.
