### ISSUE TITLE
example shows "woofy" but later refer as "barkly"

### ISSUE THREAD

**Issue by pengxh333** [Ada-Developers-Academy/ada-build#229]
the word "barkly" should be "woofy" under the example codes in the [hash](https://github.com/Ada-Developers-Academy/ada-build/tree/ruby/learning-to-code/hashes) course.

here is the screenshot: 

![image](https://user-images.githubusercontent.com/73805972/104673525-e7040d00-56af-11eb-912b-8e3731a72818.png)

**Comment by beccaelenzil** [comment]
Correction made. Just an fyi, the `ruby` branch of this repository is not being actively maintained.  To see the current version, visit this site: http://ada-developers-academy.github.io/ada-build/
