### ISSUE TITLE
Link for up-to-date catalogue of lesson videos not working

### ISSUE THREAD

**Issue by KJabbusch** [Ada-Developers-Academy/ada-build#235]
Under the Ada Build Curriculum, the link (http://ada-developers-academy.github.io/ada-build/intro-to-python/video-lesson-table.md) for the catalogue videos leads to a 404 page not found error.  Is there an alternative link provided for these, or should I just be searching through for livecode videos within the lessons themselves? Thanks!

**Comment by beccaelenzil** [comment]
thanks. the link is fixed!
