### ISSUE TITLE
Intro to Python Lesson 2 clarification

### ISSUE THREAD

**Issue by KJabbusch** [Ada-Developers-Academy/ada-build#236]
In the debugging portion of this lesson, there is a problem it wants us to debug where the input written is:
a = 3
b = 4
c = a*a + b\***b

I understand that the issue is ***, however I had corrected it to *, but later in the lesson it shows as being corrected to **. Both work in Python, but I am curious to know how we should know which one was the intended input. I'm assuming the only way to know this is to ask whoever created the code, otherwise debugging it to work may not give the intended output. This is my first time learning about Python, so I'm not sure if the ** is commonly used outside of it, which is why I had assumed it would be * initially.

**Comment by beccaelenzil** [comment]
You are right! In this way there is no way to know the intended input. I am a former math teacher, so sometimes I rely heavily on math examples. The pythagorean theorem says a^2 + b^2 = c. In python this could be `c = a*a + b*b` or `c = a**2 + b**2`.
