### ISSUE TITLE
Typo in Ada Build Curriculum

### ISSUE THREAD

**Issue by jessepope** [Ada-Developers-Academy/ada-build#241]
Location of typo outlined below through title path. Typo italicized and circled in red in screengrab from curriculum:

Ada Build Curriculum > Lesson 02: Programming Grammar > Section: Debugging > Exercise: Debugging syntax errors > "You can _clock_ on the link for a video lesson of the debugging exercise."

"clock" should be "click"

![ada build _ typo_lesson 02_debugging section](https://user-images.githubusercontent.com/80115467/110137552-9ac37800-7d96-11eb-9d15-4694ff0d7451.JPG)

**Comment by beccaelenzil** [comment]
This has been corrected. Thanks!
