### ISSUE TITLE
Lesson 7 not loading correctly

### ISSUE THREAD

**Issue by rebeccazuick** [Ada-Developers-Academy/ada-build#242]
When I attempt to open Lesson 7 of the Ada Build Curriculum (which should be entitled Dictionaries) from the video lessons link, it takes me to Lesson 8 on Inputs. When accessing Lesson 7 from the main Ada Build page, however, the link seems to work correctly and opens the correct Lesson 7.

**Comment by beccaelenzil** [comment]
Corrected. Thanks!
