### ISSUE TITLE
08-optional-user-input The input Function: int and str functions reversed

### ISSUE THREAD

**Issue by mjhugh** [Ada-Developers-Academy/ada-build#247]
Description of `int` and `str` functions are reversed, and a minor typo:

<img width="789" alt="ada_08_issue" src="https://user-images.githubusercontent.com/32968533/122862736-73a59d80-d2d6-11eb-9426-cb686e5894f4.png">

**Comment by beccaelenzil** [comment]
Correction made. Thanks!
