### ISSUE TITLE
Lesson 02 - String Concatenation and Duplication output typo

### ISSUE THREAD

**Issue by LeleCrafts** [Ada-Developers-Academy/ada-build#254]
I noticed an extra space in the output when running the second code example under String Concatenation and Duplication.  It's obviously minor, but caught my eye and I enjoyed figuring out how tweak the code to delete the extra space in the output.

Running the code as-is results in the following:

> word_1 = "home"
> word_2 = "work"
> 
> concatenated_words = word_1 + word_2 + ' '  # concatentation
> duplicated_words = 3 * concatenated_words  # duplication
> 
> print(f"These days, all I seem to do is {duplicated_words}.")
> These days, all I seem to do is homework homework homework .

Note the space between "homework" and the period.  However, rewriting concatenated_words to add the space before word_1 and eliminating it after word_2, as well as eliminating the space in the print function immediately before {duplicated_words} results in the output having no space between "homework" and the period.

> word_1 = "home"
> word_2 = "work"
> 
> concatenated_words = ' ' + word_1 + word_2  # concatentation
> duplicated_words = 3 * concatenated_words  # duplication
> 
> print(f"These days, all I seem to do is{duplicated_words}.")
> These days, all I seem to do is homework homework homework.

Many thanks for the clear, in-depth lessons, and I look forward to continuing!

**Comment by LeleCrafts** [comment]
Lesson 02 - Indexing/Slicing

> string[i:j:k] will provide a section of characters from index i up to, but not including index j, **stepping** by the interval k

Is "stepping" intended to be "stopping?"

**Comment by clarenceedmonds** [comment]
Hi, good habit of attempting different ways to fix issues. The initial code has the space only because it's concatenated with the 2 words. Another idea to potentially implement is removing the space at the end of the string value in duplicated_words before it's printed.
