### ISSUE TITLE
Lesson02_numbers_exercise Video 

### ISSUE THREAD

**Issue by mleo-nard** [Ada-Developers-Academy/ada-build#256]
The exercise is... 
Using assignment statements and string interpolation, complete the following problem in the code block below.
- Assign values to three variables x1, x2, and x3.
- Print three number equations that show the result of adding 20 to each of the variables.
- For instance, if x1 = 25, the ouput **(sp. output)** of our code should be 25 + 20 = 45

The presenter could have left the solution as the below, but I love how they took it a step further and gave an improvement to make. 

# assign values to 3 variables
x1 = 2021
x2 = 1
x3 = 13

# print the equations
print (f"{x1}+20={x1+20}")
print (f"{x2}+20={x2+20}")
print (f"{x3}+20={x3+20}")

> 2021+20=2041
> 1+20=21
> 13+20=33

The improvement on the above was to store the mathematical operation in a variable as seen below. 

# assign values to 3 variables
x1 = 2021
x2 = 1
x3 = 13

# store in another variable the value to add to the variables in line 2-4 
amount = 20
sum1 = x1+amount
sum2 = x2+amount
sum3 = x3+amount

# print the equations
print (f"{x1}+20={sum1}")
print (f"{x2}+20={sum2}")
print (f"{x3}+20={sum3}")

> 2021+20=2041
> 1+20=21
> 13+20=33

The purpose of the improvement above is to be able to quickly change the amount in one spot only should the requirements for the exercise change. For example, instead of 20, it changes to 50. However, for the output to still be correct, we need to add {amount} within the string as the value to be interpolated. So my improvement suggestion is to add the below to the video. Otherwise, an 'add 50' requirement change would output 2021+20=2071 

# assign values to 3 variables
x1 = 2021
x2 = 1
x3 = 13

# add an amount to the variables above 
amount = 50
sum1 = x1+amount
sum2 = x2+amount
sum3 = x3+amount 

# print the equations
print (f"{x1}+{amount}={sum1}")
print (f"{x2}+{amount}={sum2}")
print (f"{x3}+{amount}={sum2}")

> 2021+50=2071
> 1+50=51
> 13+50=63

**Comment by clarenceedmonds** [comment]
Thank you for the suggestion. We will look into this further.
