### ISSUE TITLE
Lesson 06_lists, exercise #4

### ISSUE THREAD

**Issue by JaimeMitchell** [Ada-Developers-Academy/ada-build#257]
Hi, I think there's an error in # exercise 4
It originally reads as:
# exercise 4
zeros = [0] * 5
print(zeros[2])

This outputs a single zero, because it's only printing the zero in the array, index [2]; However, the lesson says it should return an array that has 0's indexed from 0-4 or [0,0,0,0,0]:
The only way I was able to see that was to change the code myself to:

# exercise 4
zeros = [100] * 5
print(zeros)

Apologies if I am misunderstanding something and this is an inconvenience. If I'm not mistaken, and it is a typo, it may be helpful to change the code and then put this bit at the bottom instead of the top "...and then modify exercise 4 to create a list of 100s." after it's discussed. Still leaving "Examine the code below.  Does it look similar to anything you learned about Strings?  Predict the output" at the top. Still asking us to predict in the beginning, but leaving the modification of the code, from 0s to 100s, after the main points are made.  
Without meaning to be repetitive, but to just show exactly how it reads:

 "List Replication

Examine the code below.  Does it look similar to anything you learned about Strings?  Predict the output, and then modify exercise 4 to create a list of 100s.

# exercise 4
zeros = [100] * 5
print(zeros)

The exercise above creates an array `zeros` which looks like the table below.

_zeros_

| Index | [0] | [1] | [2] | [3] | [4] |
| :---- | :-- | :-- | :-- | :-- | :-- |
| Value |  0  |  0 |  0 | 0 |  0 |

How did `zeros` end up with 5 values? Do you remember string replication? We encountered it briefly in lesson 02. Recall that a string followed by what looks like integer multiplication will replicate and join the string as many times as the multiplication value, here treated as the replication count."

**Comment by clarenceedmonds** [comment]
Hi Jaime, the purpose of this exercise is to see how the code replicates any value within the lists or any given string by the number it is multiplied by to the right of it. The initial example uses zero so it calls the variable that is assigned the list of "0" zero. You could change the name of the variable to reflect the values that will populate it.
