### ISSUE TITLE
06_lists , for loops and range, example 1 and example 2

### ISSUE THREAD

**Issue by JaimeMitchell** [Ada-Developers-Academy/ada-build#258]
<img width="1728" alt="Screen Shot 2022-02-09 at 8 44 31 PM" src="https://user-images.githubusercontent.com/63885855/153321356-6f65d9de-c370-4d4c-95fe-6b0f700361b4.png">
<img width="1728" alt="Screen Shot 2022-02-09 at 8 42 27 PM" src="https://user-images.githubusercontent.com/63885855/153321359-2f80d7e3-3eaf-43dd-975e-21e8f9abd44e.png">

I was running this code and everything was fine, now even your code isn't working. I have closed the page, reloaded it, I have even copied and pasted the code from your original Colaboratory page to my saved page of the same lesson, and it keeps running this error, even on code that I can run in Visual Studio Code. I am not sure if this is an issue with Colaboratory? I attached two screen shots to show the code is the same on my page and yours, it also shows the error code "String object is not callable". I'm going to clear cookies on Chrome and try to problem solve this, but the fact that it's a syntax error, yet works fine with other Python debuggers is baffling me. I'm super curious and interested to know why this might happen and how to approach it. Thank you!

UPDATE: Today I opened it up and, without changing a things about the code cells, everything was working again.
                 I did clear all cookies from Google Chrome, along with history and any cache, and restarting the computer
                 the computer, BUT it didn't work right away after doing that. It only worked by giving up for the night and then 
                 opening it the next day, so I'm assuming it may be a colab bug?  I am still really curious what would have caused 
                 that debugger to bug out. A google search didn't return much, but I did gather that debuggers are not 
                 universal and that they can all have different features or differ in their performance.

**Comment by clarenceedmonds** [comment]
Sorry for just seeing this issue, but I believe and remember Collab being down for a brief moment/day around this time of submission.

**Comment by JaimeMitchell** [comment]
No worries. Thank you.
