### ISSUE TITLE
HackerRank Practice Test

### ISSUE THREAD

**Issue by JaimeMitchell** [Ada-Developers-Academy/ada-build#260]
Hi, Not sure if this is the right place to suggest there may be a possible bug in the HackerRank Test. I have double checked that my code works in Visual Study Code and the Colab environment. I ran "All Test Cases" and looked them over noticing that some have less than three accounts to tally and some have more than 3 accounts, so wrote my code to work with that successfully. I don't want to paste my code here and spoil it for others, but am curious if there's something I'm missing or just a bug in the code. I've rewritten this code a number of times to deal with the 3 inputs the HackerRank Robot will input with that given 'if' statement at the very bottom of the program, with no success. Any guidance with this would be appreciated. I can send my full program to show it works but not with HackerRank. Thank you for taking the time to read this!

**Comment by clarenceedmonds** [comment]
Hi Jaime, sorry for the delayed response. The tests are created to attempt your code with many different numbers of accounts. The initial run code has a set number of accounts to help get a general idea for handling one or many accounts. Hope this is helpful. Again sorry for the delayed response.
