### ISSUE TITLE
Typo in 03_branching

### ISSUE THREAD

**Issue by smlongino** [Ada-Developers-Academy/ada-build#262]
In the Branching lesson, there is an extra "D" in "HUNDRED":

temp = 0

if temp == 0:
    print("It's ZERO DEGREES outside!") 
elif temp == 100:
    print("It's ONE HUNDDRED DEGREES outside!")
elif temp < 50:
    print("It's a bit chilly outside") 
elif temp < 100:
    print("It's warm outside")

**Comment by clarenceedmonds** [comment]
Fixed. Removed the extra 'D'. Thanks
