### ISSUE TITLE
Typo in Branching Lesson

### ISSUE THREAD

**Issue by smlongino** [Ada-Developers-Academy/ada-build#263]
There is a typo in the instructions under the Branching Lesson. There is a second "that" after "with code such"

Exercise: Divisible by 5
Complete the program below by replacing the ... with code such that that the program outputs "x is divisible by 5" or "x is not divisible by 5" correctly (with the value for x in place of x).

**Comment by clarenceedmonds** [comment]
Fixed. Removed the extra "that". thank you.
