### ISSUE TITLE
Lesson 4 sequence

### ISSUE THREAD

**Issue by aawarnken** [Ada-Developers-Academy/ada-build#264]
In the checkends section you introduce the solution that checks for the string length first- if len(string)==0, 
however at that point you have not explained that function (len) yet and only elaborate on  in the next section- flipside. Maybe move the paragraph introducing the length function up, because you really hint on it while talking about the checkends for one character string.
Sincerely, 
Alex

**Comment by clarenceedmonds** [comment]
Noted and will review. Thanks.
