### ISSUE TITLE
Lesson 02: Programming Grammar - Code Block 1 Error

### ISSUE THREAD

**Issue by MoonQueenOG** [Ada-Developers-Academy/ada-build#265]
Hello! 
There seems to be an attachment error? 

At first glance, I cannot see the image but instead this box with the question mark.
<img width="699" alt="Screen Shot 2022-03-26 at 5 10 43 PM" src="https://user-images.githubusercontent.com/102441222/160261190-5129ff35-ea33-4c64-bda8-a0eaa955f509.png">

But when I right click and open as a new tab, I can see it perfectly. 

<img width="439" alt="Screen Shot 2022-03-26 at 5 11 54 PM" src="https://user-images.githubusercontent.com/102441222/160261214-991d845b-8dd6-46c3-b7a2-852a44d5301b.png">

<img width="695" alt="Screen Shot 2022-03-26 at 5 12 44 PM" src="https://user-images.githubusercontent.com/102441222/160261218-1911caa2-89c3-4359-aefd-41de918da9e0.png">

All the best, 
MoonQueenOG

**Comment by MoonQueenOG** [comment]
P.s., 

It's like this for the rest of the examples in this lesson :/

**Comment by clarenceedmonds** [comment]
Which browser are you using? It seems to be appearing in Chrome.
