### ISSUE TITLE
Typo on Cohort 18 Application submittable page  

### ISSUE THREAD

**Issue by MoonQueenOG** [Ada-Developers-Academy/ada-build#266]
<img width="572" alt="Screen Shot 2022-03-28 at 11 13 17 AM" src="https://user-images.githubusercontent.com/102441222/160460658-d03cb2af-aa83-4e26-8ca5-d9ce861b90a4.png">

Hello there :) 
There's an extra "Q" if I'm not mistaken. 

👯‍♀️

**Comment by clarenceedmonds** [comment]
Notified admissions about this.
