### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by levarioe** [Ada-Developers-Academy/ada-build#276]
Hello everyone! I'm very new, but wanted to put this out there. Not sure if the \n is supposed to be on a code block.

Under Intro to Programming, Order 02, under Strings, then Common Escape Sequences...its the first code block under #double quotes line 2. This is the code: phrase = "\"We're so glad you're here!\" they said.\n"

not sure if it's meant to be there. It threw me off, but then again, I'm very knew.

A shoot in the dark :-)

**Comment by resmins** [comment]
Hey!

Just think of "\n" as the "enter" button on the computer. You press "enter" to create a new line/sentence. 
So you are technically creating a new line after the previous line/sentence. 

**sentence/string in this example

"We're so glad you're here! they said.     # previous line
 THEN [Press Enter]                                 #which means new line [ \n ]
..[Empty New Line] ...                               #New Line on Standby to be used if desired

The Problem:

phrase = "\"We're so glad you're here!\" they said.\n"
print(phrase) 

"We're so glad you're here!" they said.

**Comment by blackgirlintech** [comment]
Thank you for your explanation!  I get it now!
