### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by levarioe** [Ada-Developers-Academy/ada-build#277]
Hello again. 

Under Intro to Programming, Order 02, under Strings, then String Concatenation and Duplication...code block [10] & [16] the #concatentation is misspelled in both spots

Am I suppose to correct it and go about my business/learning or am I suppose to report it? 

Please advise, thank you

**Comment by yangashley** [comment]
Thanks for opening the issue. The typo has been updated. Closing the issue.
