### ISSUE TITLE
Example Debugging problems already contain solution.

### ISSUE THREAD

**Issue by Msambere** [Ada-Developers-Academy/ada-build#300]
In the posted file for lesson 05, the "Example: Infinite loop" code already contains the debugged code. I have also noticed this issue (code for example exercise already contained the fixed/complete code) in other lessons. It seems like the master copy of the lessons was edited accidentally and now contains some of the solutions.

<img width="923" alt="Screenshot 2023-03-21 141223" src="https://user-images.githubusercontent.com/110812972/226716573-aa5f2185-a71e-4e33-a8e6-db80d11cc8a7.png">

**Comment by LauraGaleev** [comment]
I have noticed the same issue.

**Comment by yangashley** [comment]
Thanks for opening the issue. Updated exercise back to infinite loop state without the solution. Closing issue.
