### ISSUE TITLE
Lesson 4: Flipside & Checkends Already contain solutions 

### ISSUE THREAD

**Issue by valerie-valentine** [Ada-Developers-Academy/ada-build#302]
![Screenshot 2023-04-16 at 1 54 25 PM](https://user-images.githubusercontent.com/121909894/232341809-1a6449e2-399e-46b5-bf3b-9e299843f0be.png)
![Screenshot 2023-04-16 at 1 54 11 PM](https://user-images.githubusercontent.com/121909894/232341823-c5bf575d-2109-4fc4-bfe1-a40b1f61dac0.png)

**Comment by yangashley** [comment]
Thanks for opening the issue. Updated the two methods to remove solution. Closed the issue.
